### ISSUE TITLE
origianlal v2_dump.bin

### ISSUE THREAD

**Issue by Capta1nTaiwan** [GMMan/DigimonColorSpriteTool#1]
Hello, when I extracted the v2_dump.bin from my DMC, I didn't realize that the bin file I took out was corrupted. It wasn't until I changed the Japanese icons to English icons and imported the bin file and wrote it to the IC that I realized there was an issue. Now some icons appear as strange green colors. Could you kindly provide a v2 version of the bin file? Thank you.

**Comment by GMMan** [comment]
The ROM is copyrighted content, so I cannot provide a copy to you.
